#!/usr/bin/python3

import cgi

print("<html>")
print("<head>")
print("<title>Webserv</title>")
print("<style>")
print("body {")
print("    font-family: 'Nanum Gothic', sans-serif;")
print("    background-color: #FFFFFF;")
print("    margin: 0;")
print("    padding: 0;")
print("}")

print("h1 {")
print("    text-align: center;")
print("    background-color: #000000;")
print("    color: #fff;")
print("    padding: 20px 0;")
print("}")

print("form {")
print("    text-align: center;")
print("    padding: 20px;")
print("}")

print(".center-content {")
print("    text-align: center;")
print("    margin: 0 auto;")
print("    width: 200px;")
print("}")

print("input[type='text'], input[type='password'] {")
print("    width: 100%;")
print("    padding: 10px;")
print("    font-size: 16px;")
print("    margin: 10px 0;")
print("    border: 1px solid #000000;")
print("    border-radius: 4px;")
print("}")

print("input[type='submit'] {")
print("    background-color: #000000;")
print("    color: #fff;")
print("    padding: 10px 20px;")
print("    font-size: 16px;")
print("    border: none;")
print("    border-radius: 4px;")
print("    cursor: pointer;")
print("}")

print("</style>")
print("</head>")
print("<body>")
print("<h1>Webserv</h1>")
print("<form method='post' action='/cgiloginres.py'>")
print("<p>Only team members can login, pw : 1234</p>")
print("<div class='center-content'>")
print("<label for='id'>intra_id</label><br>")
print("<input type='text' name='id'><br>")
print("<label for='pw'>password</label><br>")
print("<input type='password' name='pw'><br>")
print("</div>")
print("<input type='submit' value='login'>")
print("</form>")
print("</body>")
print("</html>")
